# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: vs2017-win2016
  
variables:
  buildConfiguration: 'Release'

trigger:
  branches:
    include:
    - "*"
  paths:
    include:
    - src/Microservice.Extensions.NugetFeedTest/*

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
  
- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  inputs:
    preferBundledVersion: false

- powershell: |
   $Release_Version = "$env:GITVERSION_MAJORMINORPATCH"
   Write-Host ("##vso[task.setvariable variable=Release_Version;]$Release_Version")
  displayName: 'Setting Release variable'

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packDirectory: '$(build.artifactStagingDirectory)/PreRelease'
    configuration: $(BuildConfiguration)
    packagesToPack: 'src/Microservice.Extensions.NugetFeedTest/Microservice.Extensions.NugetFeedTest/Microservice.Extensions.NugetFeedTest.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: GITVERSION_FullSemVer

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packDirectory: '$(build.artifactStagingDirectory)/Release'
    configuration: $(BuildConfiguration)
    packagesToPack: 'src/Microservice.Extensions.NugetFeedTest/Microservice.Extensions.NugetFeedTest/Microservice.Extensions.NugetFeedTest.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: Release_Version

- task: PublishBuildArtifacts@1
