# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: vs2017-win2016
  
variables:
  buildConfiguration: 'Release'
  Major: '2'
  Minor: '0'
  Patch: '2'

name: $(BuildDefinitionName)_$(Major).$(Minor).$(Patch)

trigger:
  branches:
    include:
    - "*"
  paths:
    include:
    - src/Microservice.Extensions.NugetFeedTest/*

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
  
- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  inputs:
    preferBundledVersion: false

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packDirectory: '$(build.artifactStagingDirectory)/PreRelease'
    configuration: $(BuildConfiguration)
    packagesToPack: 'src/Microservice.Extensions.NugetFeedTest/Microservice.Extensions.NugetFeedTest/Microservice.Extensions.NugetFeedTest.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: GITVERSION_FullSemVer


- task: PublishBuildArtifacts@1
