# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: vs2017-win2016
  
variables:
  buildConfiguration: 'Release'

trigger:
  branches:
    include:
    - "*"
  paths:
    include:
    - src/Microservice.Extensions.NugetFeedTest/*

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
  
- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  inputs:
    preferBundledVersion: false

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packDirectory: '$(build.artifactStagingDirectory)'
    configuration: $(BuildConfiguration)
    packagesToPack: 'src/Microservice.Extensions.NugetFeedTest/Microservice.Extensions.NugetFeedTest/Microservice.Extensions.NugetFeedTest.csproj'
    versioningScheme: off

- task: PublishBuildArtifacts@1
