# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'
  Major: '2'
  Minor: '0'
  Patch: '0'

name: $(BuildDefinitionName)_$(Major).$(Minor).$(Patch)-$(date:yyyyMMddHHmmss)

trigger:
  branches:
    include:
    - "*"
  paths:
    include:
    - src/Microservice.Extensions.NugetFeedTest/*

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packDirectory: '$(build.artifactStagingDirectory)'
    configuration: $(BuildConfiguration)
    packagesToPack: 'src/Microservice.Extensions.NugetFeedTest/Microservice.Extensions.NugetFeedTest/Microservice.Extensions.NugetFeedTest.csproj'
    versioningScheme: byPrereleaseNumber
    major: $(Major)
    minor: $(Minor)
    patch: $(Patch)
    packTimezone: 'utc'

- task: PublishBuildArtifacts@1
