# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'

triggers:
  paths:
    include:
    - src/DataFunctions/*

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: False
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/webapi-$(Build.BuildNumber)'
    zipAfterPublish: True
    workingDirectory: src/WebAPI

- task: PublishBuildArtifacts@1
